{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8774bb8b-1283-4175-9b55-daa7ac5f90bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-01-06 19:53:34.815 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:34.817 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.713 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run E:\\python apps\\anaconda\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-01-06 19:53:35.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.722 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.724 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.725 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.727 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.728 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.729 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.732 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.735 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.736 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.737 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.743 Session state does not function when running a script without `streamlit run`\n",
      "2026-01-06 19:53:35.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.747 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.748 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.749 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.751 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.753 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.754 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-01-06 19:53:35.757 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "from sklearn.feature_extraction.text import CountVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "import pandas as pd\n",
    "\n",
    "# Page configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"News Category Chatbot\",\n",
    "    page_icon=\"📰\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# Title and description\n",
    "st.title(\"📰 News Category Chatbot\")\n",
    "st.markdown(\"---\")\n",
    "st.write(\"\"\"\n",
    "Predict the category of any news headline using AI!\n",
    "This chatbot uses Machine Learning to classify headlines into:\n",
    "- 📱 **TECH**\n",
    "- 🎬 **ENTERTAINMENT**\n",
    "- 🏛️ **POLITICS**\n",
    "- 💼 **BUSINESS**\n",
    "\"\"\")\n",
    "\n",
    "# Define categories\n",
    "categories = ['TECH', 'ENTERTAINMENT', 'POLITICS', 'BUSINESS']\n",
    "\n",
    "# Sidebar - Information\n",
    "st.sidebar.title(\"ℹ️ About\")\n",
    "st.sidebar.info(\"\"\"\n",
    "**News Category Classifier**\n",
    "- Trained on 61,060 news articles\n",
    "- Accuracy: 87.51%\n",
    "- Using: Logistic Regression + CountVectorizer\n",
    "\"\"\")\n",
    "\n",
    "# Load your trained model and vectorizer\n",
    "# Note: You'll need to save these from your Jupyter notebook first!\n",
    "\n",
    "# For now, we'll create a simple demo version\n",
    "# In production, load your actual model:\n",
    "# with open('model.pkl', 'rb') as f:\n",
    "#     model = pickle.load(f)\n",
    "# with open('vectorizer.pkl', 'rb') as f:\n",
    "#     vectorizer = pickle.load(f)\n",
    "\n",
    "# MAIN CHATBOT INTERFACE\n",
    "st.markdown(\"---\")\n",
    "st.subheader(\"🎯 Try it out!\")\n",
    "\n",
    "# Input section\n",
    "col1, col2 = st.columns([3, 1])\n",
    "\n",
    "with col1:\n",
    "    user_headline = st.text_input(\n",
    "        \"Enter a news headline:\",\n",
    "        placeholder=\"e.g., Apple Releases New iPhone 15 with Advanced Features\",\n",
    "        help=\"Type any news headline to get a category prediction\"\n",
    "    )\n",
    "\n",
    "with col2:\n",
    "    predict_button = st.button(\"🔍 Predict\", use_container_width=True)\n",
    "\n",
    "# Prediction logic\n",
    "if user_headline and predict_button:\n",
    "    # Your prediction function would go here\n",
    "    # predicted_category, confidence = predict_headline_category(user_headline)\n",
    "    \n",
    "    # Demo prediction (replace with your actual model)\n",
    "    predictions = {\n",
    "        'TECH': 0.45,\n",
    "        'ENTERTAINMENT': 0.25,\n",
    "        'POLITICS': 0.20,\n",
    "        'BUSINESS': 0.10\n",
    "    }\n",
    "    predicted_category = max(predictions, key=predictions.get)\n",
    "    confidence = predictions[predicted_category]\n",
    "    \n",
    "    # Display results\n",
    "    st.markdown(\"---\")\n",
    "    st.subheader(\"📊 Prediction Results\")\n",
    "    \n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    \n",
    "    with col1:\n",
    "        st.metric(\"Predicted Category\", predicted_category)\n",
    "    \n",
    "    with col2:\n",
    "        st.metric(\"Confidence\", f\"{confidence:.1%}\")\n",
    "    \n",
    "    with col3:\n",
    "        if confidence > 0.8:\n",
    "            st.metric(\"Reliability\", \"🟢 High\")\n",
    "        elif confidence > 0.6:\n",
    "            st.metric(\"Reliability\", \"🟡 Medium\")\n",
    "        else:\n",
    "            st.metric(\"Reliability\", \"🔴 Low\")\n",
    "    \n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    # Show confidence for all categories\n",
    "    st.subheader(\"📈 All Category Scores\")\n",
    "    df_results = pd.DataFrame({\n",
    "        'Category': list(predictions.keys()),\n",
    "        'Score': list(predictions.values())\n",
    "    }).sort_values('Score', ascending=False)\n",
    "    \n",
    "    st.bar_chart(df_results.set_index('Category'))\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"\"\"\n",
    "<div style='text-align: center'>\n",
    "    <p>Made with ❤️ using Streamlit | Powered by Machine Learning</p>\n",
    "</div>\n",
    "\"\"\", unsafe_allow_html=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
